apiVersion: apps/v1
kind: Deployment
metadata:
  name: wasmtime
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: wasmtime
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wasmtime
        k6-stack: "true"
        k6-dedicated: "true"
    spec:
      volumes:
        - configMap:
            defaultMode: 420
            name: nats-leaf-config
          name: nats-leaf-config
      containers:
        - name: wasmtime
          image: ghcr.io/cosmonic-labs/xk6-wrpc:main
          imagePullPolicy: Always
          # resources:
          #   requests:
          #     cpu: "4"
          #     memory: "8Gi"
          #   limits:
          #     cpu: "4"
          #     memory: "8Gi"
          env:
            - name: RUST_LOG
              value: error
            - name: NATS_URL
              value: nats://127.0.0.1:4222
          command:
            - wrpc-wasmtime
            - nats
            - serve
            - -n
            - $(NATS_URL)
            - --export
            - wasmtime
            - -g
            - wrpc
            - /blaster-component.wasm
        - name: nats-leaf
          image: nats:2.10-alpine
          imagePullPolicy: IfNotPresent
          args:
            - -js
            - --config
            - /nats/nats-leaf.conf
          # resources:
          #   limits:
          #     cpu: "2"
          #     ephemeral-storage: 1Gi
          #   requests:
          #     cpu: "2"
          #     ephemeral-storage: 1Gi
          #     memory: 1Gi
          securityContext:
            capabilities:
              drop:
                - NET_RAW
          volumeMounts:
            - mountPath: /nats/nats-leaf.conf
              name: nats-leaf-config
              readOnly: true
              subPath: nats-leaf.conf
