apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: blaster-component
  annotations:
    description: Blast Away
    wasmcloud.dev/authors: Cosmonic
spec:
  components:
    - name: component
      type: component
      properties:
        image: file://./build/blaster-component_s.wasm
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
