configurations:
  - references.yaml

namespace: k6

resources:
  - wasmcloud-test.yaml
  #- wasmtime-test.yaml
  - blaster-component-wasmtime.yaml

configMapGenerator:
  - name: tests
    files:
      - wasmcloud-test.js
      - wasmtime-test.js
