// Code generated by wit-bindgen-go. DO NOT EDIT.

package blaster

import (
	"go.bytecodealliance.org/cm"
)

func lift_Packet(f0 *uint8, f1 uint32, f2 *uint8, f3 uint32, f4 uint64, f5 uint64, f6 uint64) (v Packet) {
	v.ID = cm.LiftString[string](f0, f1)
	v.Payload = cm.LiftList[cm.List[uint8]](f2, f3)
	v.MemBurnMb = (uint64)(f4)
	v.CPUBurnMs = (uint64)(f5)
	v.WaitMs = (uint64)(f6)
	return
}
