// Code generated by wit-bindgen-go. DO NOT EDIT.

package blaster

// Exports represents the caller-defined exports from "xk6:wrpc/blaster@0.0.1".
var Exports struct {
	// Blast represents the caller-defined, exported function "blast".
	//
	//	blast: func(packet: packet)
	Blast func(packet Packet)
}
