// Code generated by wit-bindgen-go. DO NOT EDIT.

package blaster

// This file contains wasmimport and wasmexport declarations for "xk6:wrpc@0.0.1".

//go:wasmexport xk6:wrpc/blaster@0.0.1#blast
//export xk6:wrpc/blaster@0.0.1#blast
func wasmexport_Blast(packet0 *uint8, packet1 uint32, packet2 *uint8, packet3 uint32, packet4 uint64, packet5 uint64, packet6 uint64) {
	packet := lift_Packet((*uint8)(packet0), (uint32)(packet1), (*uint8)(packet2), (uint32)(packet3), (uint64)(packet4), (uint64)(packet5), (uint64)(packet6))
	Exports.Blast(packet)
	return
}
