apiVersion: apps/v1
kind: Deployment
metadata:
  name: wasmcloud-wadm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: wasmcloud-wadm
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wasmcloud-wadm
    spec:
      containers:
        - name: wasmcloud-wadm
          image: ghcr.io/wasmcloud/wadm:v0.17.0
          imagePullPolicy: IfNotPresent
          env:
            - name: WADM_JETSTREAM_DOMAIN
              value: default
            - name: WADM_NATS_SERVER
              value: 127.0.0.1:4222
          resources:
            limits:
              cpu: "1"
              ephemeral-storage: 1Gi
            requests:
              cpu: 500m
              ephemeral-storage: 1Gi
              memory: 2Gi
          securityContext:
            capabilities:
              drop:
                - NET_RAW
        - name: nats-leaf
          image: nats:2.10-alpine
          imagePullPolicy: IfNotPresent
          args:
            - -js
            - --config
            - /nats/nats-leaf.conf
          resources:
            limits:
              cpu: "1"
              ephemeral-storage: 1Gi
            requests:
              cpu: "1"
              ephemeral-storage: 1Gi
              memory: 1Gi
          securityContext:
            capabilities:
              drop:
                - NET_RAW
          volumeMounts:
            - mountPath: /nats/nats-leaf.conf
              name: nats-leaf-config
              readOnly: true
              subPath: nats-leaf.conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoSchedule
          key: cloud.google.com/compute-class
          operator: Equal
          value: Balanced
        - effect: NoSchedule
          key: kubernetes.io/arch
          operator: Equal
          value: amd64
      volumes:
        - configMap:
            defaultMode: 420
            name: nats-leaf-config
          name: nats-leaf-config
