apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: loki
  name: loki
spec:
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
  serviceName: loki-headless
  template:
    metadata:
      labels:
        app.kubernetes.io/name: loki
        k6-stack: "true"
    spec:
      initContainers:
        - name: volume-mount-hack
          image: busybox
          # 10001 is the id of user 'loki'
          command: ["sh", "-c", "chown -R 10001:10001 /data"]
          volumeMounts:
            - name: loki-data
              mountPath: /data
      containers:
        - args:
            - "-config.file=/etc/loki-config/loki-config.yaml"
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: SERVER_NAME
              value: $(POD_NAME)
          image: grafana/loki:3.0.1
          imagePullPolicy: IfNotPresent
          name: loki
          ports:
            - containerPort: 3100
              name: loki
              protocol: TCP
          # resources:
          #   limits:
          #     cpu: "2"
          #     ephemeral-storage: 1Gi
          #     memory: 8Gi
          #   requests:
          #     cpu: "2"
          #     ephemeral-storage: 1Gi
          #     memory: 8Gi
          securityContext:
            capabilities:
              drop:
                - NET_RAW
          volumeMounts:
            - mountPath: /etc/loki-config
              name: config
            - mountPath: /data
              name: loki-data
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      restartPolicy: Always
      shareProcessNamespace: true
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoSchedule
          key: kubernetes.io/arch
          operator: Equal
          value: amd64
      volumes:
        - configMap:
            defaultMode: 420
            name: loki
          name: config
        - emptyDir: {}
          name: pid
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: loki-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        volumeMode: Filesystem
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app.kubernetes.io/name: loki
  name: loki-headless
spec:
  clusterIP: None
  internalTrafficPolicy: Cluster
  ports:
    - appProtocol: tcp
      name: loki
      port: 3100
      protocol: TCP
      targetPort: loki
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: loki
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: loki
  name: loki
spec:
  internalTrafficPolicy: Cluster
  ports:
    - appProtocol: tcp
      name: loki
      port: 3100
      protocol: TCP
      targetPort: loki
  selector:
    app.kubernetes.io/name: loki
  sessionAffinity: None
  type: ClusterIP
