apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: opentelemetry-collector
  name: opentelemetry-collector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app.kubernetes.io/name: opentelemetry-collector
  name: opentelemetry-collector
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: opentelemetry-collector
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: opentelemetry-collector
        k6-stack: "true"
    spec:
      containers:
        - args:
            - --config=/conf/relay.yaml
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          image: otel/opentelemetry-collector-contrib:0.113.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 13133
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: opentelemetry-collector
          ports:
            - containerPort: 6831
              name: jaeger-compact
              protocol: UDP
            - containerPort: 14250
              name: jaeger-grpc
              protocol: TCP
            - containerPort: 14268
              name: jaeger-thrift
              protocol: TCP
            - containerPort: 4317
              name: otlp
              protocol: TCP
            - containerPort: 4318
              name: otlp-http
              protocol: TCP
            - containerPort: 9411
              name: zipkin
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 13133
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          # resources:
          #   limits:
          #     cpu: "1"
          #     memory: 2Gi
          #     ephemeral-storage: 1Gi
          #   requests:
          #     cpu: 500m
          #     ephemeral-storage: 1Gi
          #     memory: 2Gi
          securityContext:
            capabilities:
              drop:
                - NET_RAW
          volumeMounts:
            - mountPath: /conf
              name: opentelemetry-collector
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      serviceAccountName: opentelemetry-collector
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoSchedule
          key: kubernetes.io/arch
          operator: Equal
          value: amd64
      volumes:
        - configMap:
            defaultMode: 420
            items:
              - key: otel-config.yaml
                path: relay.yaml
            name: opentelemetry-collector
          name: opentelemetry-collector
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  name: opentelemetry-collector-headless
spec:
  clusterIP: None
  internalTrafficPolicy: Cluster
  ports:
    - name: grpc
      port: 4317
      protocol: TCP
      targetPort: 4317
    - name: http
      port: 4318
      protocol: TCP
      targetPort: 4318
  selector:
    app.kubernetes.io/name: opentelemetry-collector
  sessionAffinity: None
  type: ClusterIP
